server:
  port: 8071
spring:
#  zipkin:
#    base-url: http://127.0.0.1:9411/  #zipkin server的请求地址
#    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
#  sleuth:
#    sampler:
#      probability: 1.0  #采样的百分比
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update  # 也根据model类生成表,即使表结构改变了,表中的行仍然存在,不会删除以前的行
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect   #默认innodb
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
rocketmq:
  name-server: 43.143.153.172:9876 #rocketMQ服务的地址
