spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: springcloud-provider-user
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
spring:
  profiles: test
  application:
    name: springcloud-provider-user
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/