server:
  port: 80

#Eureka
eureka:
  client:
    # 表示是否向 Eureka 注册中心注册自己(这个模块本身是服务器,所以不需要)
    register-with-eureka: false
    # Eureka监控页面~
    service-url:
      # 集群（关联）：7002、7001、7003
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#  显示no instance的可以把fetch-registry改为true,registry-with-eureka改为true